# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('_ext'))

# -- Project information -----------------------------------------------------

project = 'PyCon JP Association'
copyright = '2022, PyCon JP Association'
author = 'PyCon JP Association'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "myst_parser",
    "myst_patch",
    'sphinxext.opengraph',
]

myst_enable_extensions = [
    "fieldlist",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'shibuya'

html_title = 'PyCon JP Association'

html_last_updated_fmt = '%Y-%m-%d'

html_show_copyright = False

html_logo = "_static/pyconjp_logo.png"

html_favicon = '_static/favicon.png'

# https://shibuya.lepture.com/customisation/colors/
# https://shibuya.lepture.com/customisation/social/
html_theme_options = {
    "accent_color": "red",
    "github_url": "https://github.com/pyconjp/www.pycon.jp/",
    "twitter_url": "https://x.com/pyconjapan",
    "youtube_url": "https://www.youtube.com/@PyConJP",
}

# options for Open Graph
# https://github.com/wpilibsuite/sphinxext-opengraph
ogp_site_url = "https://www.pycon.jp/"
# ogp_image = "https://www.pycon.jp/_static/pyconjp_logo.png"
# ogp_use_first_image = True

# https://sphinxext-opengraph.readthedocs.io/en/latest/socialcards.html
ogp_social_cards = {
    "enable": True,
    "image": "_static/pyconjp_logo.png",
    "font": "Noto Sans CJK JP",
}

# font settings for macOS and Windows
if sys.platform == "darwin":
    ogp_social_cards["font"] = "Hiragino Maru Gothic Pro"
elif sys.platform == "win32":
    ogp_social_cards["font"] = "MS Gothic"

# options for linkcheck
# https://www.sphinx-doc.org/ja/master/usage/configuration.html#options-for-the-linkcheck-builder
linkcheck_ignore = [
    r"https://pyconjp.atlassian.net/.*",
    r"https://drive.google.com/.*",
    r"https://docs.google.com/.*",
    r"http://trac.pycon.jp/.*",
]
