# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('_ext'))

# -- Project information -----------------------------------------------------

project = 'PyCon JP Association'
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" src="https://i.creativecommons.org/l/by/4.0/88x31.png"></a> www.pycon.jp by PyCon JP Association is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'
author = 'PyCon JP Association'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "myst_parser",
    "myst_patch",
    'sphinxext.opengraph',
]

myst_enable_extensions = [
    "fieldlist",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'shibuya'

html_title = 'PyCon JP Association'

html_last_updated_fmt = '%Y-%m-%d'

html_show_copyright = True

html_logo = "_static/pyconjp_logo.png"

html_favicon = '_static/favicon.png'

html_theme_options = {
    # https://shibuya.lepture.com/customisation/colors/
    "accent_color": "red",
    # https://shibuya.lepture.com/customisation/navbar/
    "nav_links": [
        {
            "title": "Event",
            "url": "event",
            "children": [
                {
                    "title": "🐴 PyCon JP 2026",
                    "url": "https://2026.pycon.jp/",
                    "external": True,
                },
                {
                    "title": "🐍 PyCon JP 2025",
                    "url": "https://2025.pycon.jp/",
                    "external": True,
                },
            ],
        },
        {
            "title": "Website",
            "children": [
                {
                    "title": "📘 Python Boot Camp Text",
                    "url": "https://pycamp.pycon.jp/",
                    "summary": "Python Boot Campで使用するテキスト",
                    "external": True,
                },
                {
                    "title": "📺 PyCon JP TV",
                    "url": "https://tv.pycon.jp",
                    "summary": "PyCon JP Associationが主催するYouTubeライブ",
                    "external": True,
                },
            ],
        },
        {
            "title": "Media",
            "url": "media",
            "children": [
                {
                    "title": '<iconify-icon icon="simple-icons:blogger"></iconify-icon> PyCon JP Blog',
                    "url": "https:.//pyconjp.blogspot.com/",
                    "summary": "",
                    "external": True,
                },
                {
                    "title": '<iconify-icon icon="simple-icons:youtube"></iconify-icon> YouTube',
                    "url": "https://www.youtube.com/@PyConJP/",
                    "external": True,
                },
                {
                    "title": '<iconify-icon icon="simple-icons:flickr"></iconify-icon> Flickr',
                    "url": "https://www.flickr.com/photos/pyconjp/albums",
                    "external": True,
                },
            ],
        },
    ],
    # https://shibuya.lepture.com/customisation/social/
    "github_url": "https://github.com/pyconjp/www.pycon.jp/",
    "twitter_url": "https://x.com/pyconjapan",
    "youtube_url": "https://www.youtube.com/@PyConJP",
}

# https://shibuya.lepture.com/customisation/sidebar/
html_context = {
    "source_type": "github",
    "source_user": "pyconjp",
    "source_repo": "www.pycon.jp",
    "source_edit_template": "https://github.com/pyconjp/www.pycon.jp/blob/master/source/{0}",
}

# options for Open Graph
# https://github.com/wpilibsuite/sphinxext-opengraph
ogp_site_url = "https://www.pycon.jp/"
# ogp_image = "https://www.pycon.jp/_static/pyconjp_logo.png"
# ogp_use_first_image = True

# https://sphinxext-opengraph.readthedocs.io/en/latest/socialcards.html
ogp_social_cards = {
    "enable": True,
    "image": "_static/pyconjp_logo.png",
    "font": "Noto Sans CJK JP",
}

# font settings for macOS and Windows
if sys.platform == "darwin":
    ogp_social_cards["font"] = "Hiragino Maru Gothic Pro"
elif sys.platform == "win32":
    ogp_social_cards["font"] = "MS Gothic"

# options for linkcheck
# https://www.sphinx-doc.org/ja/master/usage/configuration.html#options-for-the-linkcheck-builder
linkcheck_ignore = [
    r"https://pyconjp.atlassian.net/.*",
    r"https://drive.google.com/.*",
    r"https://docs.google.com/.*",
    r"http://trac.pycon.jp/.*",
]
